config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :posts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  # アソシエーション
  belongs_to :user

  # 画像ファイルを紐付け
  has_one_attached :image

  # 空の値を登録できないようにバリデーション
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # アソシエーション
  has_many :posts, dependent: :destroy

  # 空のデータを保存できないようバリデーション
  validates :nickname, :birthday, presence: true
  # passwordのバリデーション
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates :password, format: { with: PASSWORD_REGEX }, length: { minimum: 8, maximum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :birthday])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"] 
    end
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :move_to_index, except: [:index, :show]
  def index
    @posts = Post.includes(:user).order('created_at DESC')
  end

  def new
    # binding.pry
    @post = Post.new
  end

  def create
    # binding.pry
    @post = Post.new(post_params)
    if @post.valid?
      @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  def post_params
    params.require(:post).permit(:memo, :image).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>i Note</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js" integrity="sha384-pjaaA8dDz/5BgdFUPX6M/9SUZv4d12SUPF0axWc+VRZkx5xU3daN+lYb49+Ax+Tl" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画像一覧 %>
  <div class='post-contents'>
    <ul class='post-lists'>
      <%# 画像一覧 %>
      <%= render "shared/index", posts: @posts %>
      <%# /画像一覧 %>
      <%# 画像がない場合のダミー %>
      <% if @posts.where('id >= 1').blank? %>
        <li class='list'>
          <div class='post-img-content'>
            <%= link_to new_post_path do %>
              <%= image_tag "white_image.jpg", class: "post-img" %>
            <% end %>
          </div>
        </li>
      <% end %>
      <%# //画像がない場合のダミー %>
    </ul>
  </div>
  <%# //画像一覧 %>
</div>

app/views/posts/new.html.erb
<%= render "shared/second_header" %>
<%= form_with model: @post, url: posts_path, class: 'registration-main', local: true do |f| %>
  <div class='form-wrap'>
    <div class='form-header'>
      <h1 class='form-header-text'>
        投稿
      </h1>
    </div>
    <div class="form-group">
      <div class="img-select cursor-poimter" onClick="$('#upfile').click()">
        <a class="img-select-text">画像を選択</a>
        <%= image_tag 'upload_icon.png',class:"img-select-icon" %>
      </div>
      <div class="image-list"id="image-list"></div>
      <%= f.file_field :image, style:"display:none;", id:"upfile" %>
      <% if @post.errors.include?(:image) %>
        <p style="color: red;"><%= @post.errors.full_messages_for(:image).first %></p>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.text_area :memo, class:"memo-text-area", id:"memo", placeholder:"ひとこと" %>
    </div>
    <div class="form-group">
      <h2 class='form-bottom-text'>
      </h2>
    </div>
    <div class='register-btn'>
      <%= f.submit "アップロード", id:"img-submit", class:"post-bk-btn" %>
    </div>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <%= link_to image_tag("inote_logo.png", class:"inote-icon"), "/" %>
  <div class='search-bar-contents'>
    <%= form_with url: '#', local: true, method: :get, class: "search-form" do |form| %>
      <%= form.text_field :keyword, placeholder: "検索する", class: "input-box" %>
      <button class="search-button">
        <%= image_tag "search_icon.png", class:"search-icon" %>
      </button>
    <% end %>
  </div>
  <div>
    <% if user_signed_in? %>
      <%= link_to image_tag('upload_icon_2.png', class: "devise_icon"), new_post_path %>
    <% end %>
  </div>
  <div class='nav'>
    <ul class='lists-right'>
      <%# ログインの有無で表示切り替え%>
      <% if user_signed_in? %>
        <li id="user_nickname_box"><%= link_to current_user.nickname, "#", class: "user-nickname", id: "user-nickname" %></li>
        <li><%= link_to image_tag('logout_icon.png', class: "devise_icon"), destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to image_tag('login_icon.png', class: "devise_icon"), user_session_path, class: "login" %></li>
        <li><%= link_to image_tag('signup_icon.png', class: "devise_icon"), new_user_registration_path, class: "sign-up" %></li>
      <%# //ログインの有無で表示切り替え%>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_index.html.erb
<% posts.each do |post| %>
  <li class='list'>
    <div class='post-img-content'>
      <%#= link_to post_path(post.id) do %>
      <%= link_to "#" do %>
        <%= image_tag post.image, class: "post-img" %>
      <% end %>
    </div>
  </li>
<% end %>

<div class="sign_modal_wrapper"></div>

app/views/shared/_second_header.html.erb
<header class='top-page-second-header'>
  <%= link_to image_tag("inote_logo.png", class:"inote-icon inote-secod-icon"), "/" %>
</header>